// Place this in order from highest expected frequency
// to lowest.

#define OBJID_NULL 0

// Items ending with _E are spawned from enemies and are hit-tested by the player object.
#define OBJID_FIREBALL 100

#define OBJID_GENERICPROJECTILE 148
#define OBJID_GENERICPROJECTILE_E 149

#define OBJID_START_OF_DMA_LIGHT_SPRITES 150

#define OBJID_BUBBLE_E 150

#define OBJID_END_OF_DMA_LIGHT_SPRITES 199

// Note that the invisible hitbox is NOT in this group.
#define OBJID_CONST_END_OF_OBJECTS_WITH_HITBOXES 199
#define OBJID_FX_SMOKE 200

#define OBJID_SYS_IMPACT 298

#define OBJID_CONST_END_OF_UNSORTED_SPRITES 299
#define OBJID_START_OF_DMA_SPRITES 300

#define OBJID_SLIME 300
#define OBJID_PLAYER 598

#define OBJID_END_OF_DMA_SPRITES 599

// Invisible hitboxes
#define OBJID_HITBOX_INVISIBLE 600
#define OBJID_HITBOX_INVISIBLE_E 601

// Interactables (non-NPC objects)
#define OBJID_START_OF_INTERACTABLES 700
#define OBJID_INTERACTABLE_SWITCH_WALL 700
#define OBJID_INTERACTABLE_SWITCH_FLOOR 701
#define OBJID_INTERACTABLE_BLOCKER_FLOOR 702
#define OBJID_INTERACTABLE_BLOCKER_DOOR_NS 703
#define OBJID_INTERACTABLE_BLOCKER_DOOR_EW 704

#define OBJID_INTERACTABLE_SIGN_WALL 710

#define OBJID_DROP_REC_MEAT 800
#define OBJID_DROP_MONEY 810

#define OBJID_END_OF_INTERACTABLES 900

#define OBJID_SPAWNER_ENEMY 1000

#define OBJID_SYS_TARGET 65500

#define PAL_PLAYER 0
#define PAL_FIREBALL 2
#define PAL_SLIME 1
#define PAL_FX_SMOKE 2
#define PAL_FX_SHADOW 2
#define PAL_SYS_TARGET 2
#define PAL_SYS_IMPACT 2
#define PAL_BUBBLE_E 2

#define PAL_DROP_REC_MEAT 2
#define PAL_DROP_MONEY 2

#define PAL_INTERACTABLE_SIGN_WALL 7
#define PAL_INTERACTABLE_SWITCH_WALL 7
#define PAL_INTERACTABLE_SWITCH_FLOOR 7
#define PAL_INTERACTABLE_BLOCKER_FLOOR 7
#define PAL_INTERACTABLE_BLOCKER_DOOR 7
