#ifndef SEQ_MODULE1_H
#define SEQ_MODULE1_H

#include <stdint.h>
#include "consts.h"
#include "consts_snd.h"
#include "defs_structs.h"
#include "vars_extern_snd.h"

// Module1 Song Instrument Bank (Slots 0..4)
const struct sample_list_entry_ins data_snd_instruments_module1[] = 
{
    {0, (void *)&data_snd_smp_module1_smp1, 540, ((9363l * 4096l) / 32000l), 0x0000, 0, 60},
    {1, (void *)&data_snd_smp_module1_smp2, 540, ((4555l * 4096l) / 32000l), 0x0000, 0, 60},
    {2, (void *)&data_snd_smp_module1_smp4, 540, ((9363l * 4096l) / 32000l), 0x0000, 0, 60},
    {3, (void *)&data_snd_smp_module1_smp5, 1494, ((44125l * 4096l) / 32000l), (0x0f | (0x03 << 4) | (0x01 << 7) | (0x13 << 8) | (0x07 << 13)), 0xffff, 60},
    {4, (void *)&data_snd_smp_module1_smp6, 198, ((7354l * 4096l) / 32000l), (0x0f | (0x03 << 4) | (0x01 << 7) | (0x13 << 8) | (0x07 << 13)), 0xffff, 60},
    {0, 0, 0, 0x1000, 0x0000, 0, 0},
};

HUGE const uint8_t data_seq_module1_t1[] = {
    // --- Order Call Script ---
    SEQ_SET_INS(0),
    SEQ_SET_VOL(31, 31),
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(53), // Pattern 1
    SEQ_CALL_SUB(53), // Pattern 1
    SEQ_RESTART,

    // --- Pattern 0 Subroutine (Offset: 18) ---
    SEQ_SET_INS(0),
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    SEQ_RET,

    // --- Pattern 1 Subroutine (Offset: 53) ---
    SEQ_SET_INS(0),
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    60,
    SEQ_WAIT_2,
    SEQ_RET,

};

HUGE const uint8_t data_seq_module1_t2[] = {
    // --- Order Call Script ---
    SEQ_SET_INS(2),
    SEQ_SET_VOL(31, 31),
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(56), // Pattern 1
    SEQ_CALL_SUB(56), // Pattern 1
    SEQ_RESTART,

    // --- Pattern 0 Subroutine (Offset: 18) ---
    SEQ_WAIT_1,
    SEQ_SET_INS(2),
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_1,
    72,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_1,
    72,
    SEQ_WAIT_0,
    72,
    SEQ_RET,

    // --- Pattern 1 Subroutine (Offset: 56) ---
    SEQ_WAIT_1,
    SEQ_SET_INS(2),
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_1,
    72,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_2,
    72,
    SEQ_WAIT_1,
    72,
    SEQ_WAIT_0,
    72,
    SEQ_RET,

};

HUGE const uint8_t data_seq_module1_t3[] = {
    // --- Order Call Script ---
    SEQ_SET_INS(1),
    SEQ_SET_VOL(31, 31),
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(38), // Pattern 1
    SEQ_CALL_SUB(38), // Pattern 1
    SEQ_RESTART,

    // --- Pattern 0 Subroutine (Offset: 18) ---
    SEQ_WAIT_3,
    SEQ_SET_INS(1),
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_2,
    SEQ_RET,

    // --- Pattern 1 Subroutine (Offset: 38) ---
    SEQ_WAIT_3,
    SEQ_SET_INS(1),
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_6,
    72,
    SEQ_WAIT_2,
    SEQ_RET,

};

HUGE const uint8_t data_seq_module1_t4[] = {
    // --- Order Call Script ---
    SEQ_SET_INS(3),
    SEQ_SET_VOL(31, 31),
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(85), // Pattern 1
    SEQ_CALL_SUB(85), // Pattern 1
    SEQ_RESTART,

    // --- Pattern 0 Subroutine (Offset: 18) ---
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    SEQ_SET_INS(3),
    38,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    38,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    38,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    38,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    36,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    36,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    36,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    36,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    43,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    43,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    43,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    43,
    SEQ_WAIT_0,
    SEQ_RET,

    // --- Pattern 1 Subroutine (Offset: 85) ---
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    SEQ_SET_INS(3),
    43,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    43,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    43,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    43,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    46,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    46,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    46,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    46,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    41,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    48,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    48,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    48,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    48,
    SEQ_WAIT_0,
    SEQ_RET,

};

HUGE const uint8_t data_seq_module1_t5[] = {
    // --- Order Call Script ---
    SEQ_SET_INS(4),
    SEQ_SET_VOL(31, 31),
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(18), // Pattern 0
    SEQ_CALL_SUB(57), // Pattern 1
    SEQ_CALL_SUB(57), // Pattern 1
    SEQ_RESTART,

    // --- Pattern 0 Subroutine (Offset: 18) ---
    SEQ_SET_INS(4),
    74,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    76,
    SEQ_WAIT_0,
    77,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_15,
    79,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    77,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    72,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    74,
    SEQ_WAIT_0,
    76,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_15,
    77,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    76,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    SEQ_RET,

    // --- Pattern 1 Subroutine (Offset: 57) ---
    SEQ_SET_INS(4),
    79,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    81,
    SEQ_WAIT_0,
    82,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_15,
    84,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    82,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    77,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    79,
    SEQ_WAIT_0,
    81,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_15,
    82,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    81,
    SEQ_WAIT_0,
    SEQ_NOTE_CUT,
    SEQ_WAIT_1,
    SEQ_RET,

};

#endif // SEQ_MODULE1_H
